### ISSUE TITLE
String to Date type conversion problem.

### ISSUE THREAD

**Issue by AleksMeshkov** [oliversturm/devextreme-query-mongodb#10]
Hi,

I'm trying to filter data by Date type. Here's my filter:

![image](https://user-images.githubusercontent.com/1904894/44657734-97e9ae80-aa06-11e8-9cd3-651d5a4d79d1.png)

I've read this:

![image](https://user-images.githubusercontent.com/1904894/44657713-7b4d7680-aa06-11e8-8291-36c93f317554.png)

I don't get how can I convert string to Date type. 

![image](https://user-images.githubusercontent.com/1904894/44657638-2ad61900-aa06-11e8-9c85-136d51401c72.png)

I thought this would be done by library but seems It just builds a filterPipeline with string instead of Date value.

Thanks!

**Comment by oliversturm** [comment]
It's been a while since I looked into this, but I know that my application filters correctly by date fields. You don't mention what your actual problem is - does the filter not execute correctly? Do you see an exception or similar?

**Comment by AleksMeshkov** [comment]
Hey, @oliversturm! Thanks for the quick reply.

>> You don't mention what your actual problem is - does the filter not execute correctly? Do you see an exception or similar?

Yes. It doesn't convert string `"2018-08-14T21:00:00.000Z"` to Date. It just passes it as a sting value (see the debug screen above) to the Mongo driver while latter expects a Date type value.

**Comment by oliversturm** [comment]
And this results in an exception from the MongoDB driver? Sorry I'm harping on about this, but I seem to remember that this format works just fine with the driver in my setup. I'll check into it in more detail when I find some time later, but for now I'm just trying to clarify that this definitely doesn't work for you. Can you post some details on the error you see, and the versions of MongoDB and the mongodb npm package you're using?

**Comment by AleksMeshkov** [comment]
Nope, there's no exception. But because of this Mongo returns nothing.

**Comment by AleksMeshkov** [comment]
But if I manually convert string to Date type Mongo filters and returns all the data I need

![image](https://user-images.githubusercontent.com/1904894/44659802-19910a80-aa0e-11e8-980a-2bc04efc136e.png)

**Comment by AleksMeshkov** [comment]
>> I'll check into it in more detail when I find some time later, but for now I'm just trying to clarify that this definitely doesn't work for you. 

You're right here, I don't use the same approach you showed in your demoDbServer example.

I get Mongo driver instance (https://mongoosejs.com/docs/api.html#connection_Connection-db) from Mongoose ODM (4.13.9) 
Although I have a connect-mongo@2.0.1

**But**.

I've just tried it with native MongoDb driver. The same issue.
I see it when set breakpoint in node_modules/devextreme-query-mongodb/index.js at the 1075 line.

![image](https://user-images.githubusercontent.com/1904894/44666436-15bab380-aa21-11e8-8727-e609fd36175d.png)

**Comment by oliversturm** [comment]
Bear with me - I've done a cross check with some demo code where I knew I was using Date type data, and I found that there's definitely a difference in handling between that demo code (which works) and this library project. I need to double check whether the conversion code was somehow dropped for the stand-alone module or whatever else happened to it...

**Comment by AleksMeshkov** [comment]
Thank you @oliversturm

For now I made a workaround for myself.

```
if (options.loadOptions && options.loadOptions.filter) {
    for (let el of options.loadOptions.filter) {
      if (Array.isArray(el)) {
        if (el[2] && !!Date.parse(el[2])) {
          el[2] = new Date(el[2]);
        }
      }
    }
  }
```

**Comment by oliversturm** [comment]
Yes - of course this would fail for more complex filter structures. In the demo code I mentioned I have recursive "fixers" that do something similar, but I don't remember what happened to that code for this project.

**Comment by AleksMeshkov** [comment]
>Yes - of course this would fail for more complex filter structures.

Totally agree. I'll be waiting for the fix. Thanks again.

**Comment by oliversturm** [comment]
I've had a more detailed look and I found that the functionality in question is in the project after all. You can see in [parseOrFix](https://github.com/oliversturm/devextreme-query-mongodb/blob/master/src/options.js#L130) how functionality from [the value-fixers package](https://github.com/oliversturm/value-fixers) is called, and this includes [a function that fixes dates](https://github.com/oliversturm/value-fixers/blob/master/src/index.js#L5).

My suspicion is therefor that your filter is constructed in some other way than by calling `getOptions` - correct? In that case you can probably use the helpers from value-fixers to do the job. Please let me know if this helps - perhaps I'm missing something.

**Comment by oliversturm** [comment]
Another thought - perhaps it isn't clearly documented - the process of "fixing" values (which includes converting strings to other types) must be executed, by means of the value-fixers functionality or otherwise, *before* query options are passed to the `query` function.

**Comment by AleksMeshkov** [comment]
Here how I use getOptions function. May be I don't get how to use it properly?

Here's my `req.query` object.
![image](https://user-images.githubusercontent.com/1904894/44671609-a8ae1a80-aa2e-11e8-96e5-0ede8b20fcb3.png)

And here's the result of the getOptions function.

![image](https://user-images.githubusercontent.com/1904894/44672183-61c12480-aa30-11e8-9bb0-07fa25980955.png)

**Comment by oliversturm** [comment]
This is quite strange. With your `getOptions` call, you don't need to pass in a schema - the schema applies to your own data, not to the parameters of the query, so there's no need to specify schema information for the `skip` and `take` values. However, I don't see anything wrong with the data. I have tested the regular expressions manually against the data from your screenshot, and I can't see a reason why the values would not be converted. Can you place a breakpoint [in the fixDate function](https://github.com/oliversturm/value-fixers/blob/master/src/index.js#L6) (follow the link to see exactly where - you can find the file in your `node_modules` folder) and see what happens there? Alternatively, debug into the getOptions call and see what happens, if and when the fixers are called (or not).

You should see how the values from your query are passed through and tested. When you encounter the date strings, `regexIso8601` should return a match and the value should be converted into a Date. Apparently this isn't happening for you somehow, but I don't have an idea at the moment why.

**Comment by oliversturm** [comment]
I think I might have found what the problem is. It looks from your screenshot as if the value filter in your `req.query` is actually not an array - it's a string encoding an array. Right? 

If so, then the problem is perhaps that the `getOptions` algorithm decodes the string one time, but then doesn't make any further passes to deal with the embedded values and their types.

**Comment by oliversturm** [comment]
With the filter parameter as a string, I can now reproduce what you're seeing. I'll fix that asap.

**Comment by AleksMeshkov** [comment]
works like a charm. thank you, @oliversturm!

**Comment by oliversturm** [comment]
[Release v2.0.5](https://github.com/oliversturm/devextreme-query-mongodb/releases/tag/v2.0.5) contains the fix now.

@AleksMeshkov You're welcome, thank you for reporting the issue!
