### ISSUE TITLE
"errorMessage":"regeneratorRuntime is not defined"

### ISSUE THREAD

**Issue by jonathanalberghini** [oliversturm/devextreme-query-mongodb#37]
Has anyone ever seen this issue?

"errorType":"ReferenceError"
"errorMessage":"regeneratorRuntime is not defined"
"stack":[17 items
0:"ReferenceError: regeneratorRuntime is not defined"
1:"    at Object.<anonymous> (/var/task/node_modules/devextreme-query-mongodb/dist/pipelines.js:5:15)"
2:"    at Module._compile (internal/modules/cjs/loader.js:1085:14)"
3:"    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)"
4:"    at Module.load (internal/modules/cjs/loader.js:950:32)"
5:"    at Function.Module._load (internal/modules/cjs/loader.js:790:12)"
6:"    at Module.require (internal/modules/cjs/loader.js:974:19)"
7:"    at Module.Hook._require.Module.require (/var/task/node_modules/require-in-the-middle/index.js:80:39)"
8:"    at require (internal/modules/cjs/helpers.js:93:18)"
9:"    at Object.<anonymous> (/var/task/node_modules/devextreme-query-mongodb/dist/index.js:9:16)"
10:"    at Module._compile (internal/modules/cjs/loader.js:1085:14)"
11:"    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)"
12:"    at Module.load (internal/modules/cjs/loader.js:950:32)"
13:"    at Function.Module._load (internal/modules/cjs/loader.js:790:12)"
14:"    at Module.require (internal/modules/cjs/loader.js:974:19)"
15:"    at Module.Hook._require.Module.require (/var/task/node_modules/require-in-the-middle/index.js:80:39)"
16:"    at require (internal/modules/cjs/helpers.js:93:18)"

**Comment by oliversturm** [comment]
I think this means you're not loading `babel-polyfill` [as described here](https://github.com/oliversturm/devextreme-query-mongodb/wiki#for-v2x).
