### ISSUE TITLE
ERROR: TypeError: item._id.toHexString is not a function

### ISSUE THREAD

**Issue by saikrishnareddy70323** [oliversturm/devextreme-query-mongodb#41]

**Comment by oliversturm** [comment]
Without context I have no idea why you're seeing this issue, but it's related to the [`replaceIds` processing option](https://github.com/oliversturm/devextreme-query-mongodb/wiki/QueryAPI#processing-option-replaceids). If this processing doesn't make sense in your context, I suggest you switch it off.
