### ISSUE TITLE
replaceIds: false  processing options not working

### ISSUE THREAD

**Issue by appsforheroes** [oliversturm/devextreme-query-mongodb#45]
I am sending replaceIds like below  for query.
`      {
        replaceIds: false,
      } `

 always querySimple function calls  r.map(replaceId) which is same for true or false. after version 2.0.4 it's always like that.
 
 
  ` 

    var mainQueryResult = function mainQueryResult() {
      return aggregateCall(collection, [].concat(_toConsumableArray(contextOptions.preProcessingPipeline), _toConsumableArray(completeFilterPipelineDetails.pipeline), _toConsumableArray(sortPipeline), _toConsumableArray(skipTakePipeline), _toConsumableArray(selectPipeline), _toConsumableArray(removeNestedFieldsPipeline)), 'mainQueryResult').toArray().then(function (r) {
        return r.map(replaceId);
      }).then(function (r) {
        return { data: r };
      });
    };

    return Promise.all([mainQueryResult()].concat(_toConsumableArray(totalCount(collection, completeFilterPipelineDetails)))).then(merge).then(summary(collection, completeFilterPipelineDetails));
 `

**Comment by appsforheroes** [comment]
after 2.0.4 version I couldn't find any place to check replaceIds value.

**Comment by oliversturm** [comment]
Thanks for the report and the PR. I think you're right that the option is ignored for some reason. I'm looking into it.

**Comment by oliversturm** [comment]
Fix is published with v2.0.16 now: https://www.npmjs.com/package/devextreme-query-mongodb/v/2.0.16
