### ISSUE TITLE
DevExtreme data store for node.js

### ISSUE THREAD

**Issue by PurwadiPw** [oliversturm/devextreme-query-mongodb#48]
will it support other databases like mysql or postgresql?

in case with a node.js server.

**Comment by oliversturm** [comment]
In short, the answer is "no". Here are details that may be helpful:

Any database could theoretically be targeted using the same technical approach `devextreme-query-mongodb` uses, i.e. work as an adapter to translate the DevExtreme query structures into a database specific call format on the server. However, the reason this was the best approach to support MongoDB is that other existing standard mechanisms do not support the document-centric NoSQL MongoDB out of the box.

For MySQL or PostgreSQL, other approaches are possible. For instance, [this repository](https://github.com/DevExpress-Examples/XPO_how-to-implement-odata4-service-with-xpo-netcore) demonstrates how to create an OData server, which can be bound directly as [documented here](https://js.devexpress.com/DevExtreme/Guide/Data_Binding/Specify_a_Data_Source/OData/).
[This blog post](https://community.devexpress.com/blogs/news/archive/2022/06/20/a-one-click-solution-for-role-based-access-control-asp-net-core-web-api-services-via-entity-framework-core-and-xpo-v22-1.aspx) points to a newer solution that uses the [Backend WebAPI Service](https://docs.devexpress.com/eXpressAppFramework/403394/backend-web-api-service) to achieve similar results.

These approaches are illustrated on the DevExpress site using a .NET based runtime. I expect in most cases that should not make a difference these days -- running a .NET container is just as easy as running a Node.js one. However, it is possible to set up a server running on Node that still uses OData (numerous packages exist on npmjs.com that may help you to do this), or of course you could use a different sort of data service that can be accessed using the features of the [DevExtreme Data Layer](https://js.devexpress.com/DevExtreme/Guide/Data_Binding/Data_Layer/#Overview).
