### ISSUE TITLE
Cannot find module 'express'

### ISSUE THREAD

**Issue by botbiz** [oliversturm/devextreme-query-mongodb#9]
When im trying to run your DemoDataServer script he throws me this error:

![image](https://user-images.githubusercontent.com/13471115/44599605-45618580-a7ad-11e8-935f-a80f05307dd6.png)

**Comment by oliversturm** [comment]
It looks to me like you need to properly initialize your project - see the warnings generated during `npm install`. You should run `npm init` in the directory and then install dependencies with `npm install express mongodb morgan cors babel-polyfill` (mongodb may be pulled in by devextreme-query-mongodb, but express, morgan and cors won't be).

And of course you'll need to be running mongodb locally, or modify the connection URL to something that works for you.

**Comment by botbiz** [comment]
Ok, i wasn't properly initializing my project. After i did it now hes throwing me this error in the image. It looks like some config for mongodb. I have a instace running in this same machine. Maybe something relataded to your last phrase. 

![image](https://user-images.githubusercontent.com/13471115/44682138-fae44100-aa18-11e8-8013-4da1cd76f55b.png)

Sorry for the begginer mistakes, but i know too little about node.js, just doing this because it seems to be the best way to connect to mongodb.

**Comment by oliversturm** [comment]
Sorry about the delay. Your problem is that you've just copied and pasted the code from the wiki page. As a result, the code is looking for an SSL certificate - unless you have one somewhere, you're probably better off commenting those nine lines at the end of the sample where SSL initialization is performed.
